FROM centos:latest
ENV LANG=en_US.UTF-8
COPY nextlinux/ /root/nextlinux/
RUN yum -y update && yum -y install epel-release && yum -y install python-pip rpm-python dpkg && yum clean all && cd /root/nextlinux && pip install --upgrade . && nextlinux feeds sync && rm -rf /root/.nextlinux/data/* && echo >> /root/.nextlinux/conf/config.yaml && echo "log_file: '/var/log/nextlinux.log'" >> /root/.nextlinux/conf/config.yaml && echo "debug_log_file: '/var/log/nextlinux.log'" >> /root/.nextlinux/conf/config.yaml && nextlinux query
CMD tail -F /var/log/nextlinux.log
