---
- hosts: docker
  become: true
  become_user: root

  tasks:

  - block:
    - name: install EPEL
      yum: name=epel-release state=latest

    - name: install dependencies (CentOS)
      yum: name={{item}} state=latest
      with_items:
        - python-pip
        - graphviz
        - rpm-python
        - dpkg

    - name: install Nextlinux
      pip: name=nextlinux
    when: ansible_distribution == 'CentOS'

  - block:
    - name: install dependencies (Ubuntu)
      apt: name={{item}} state=latest
      with_items:
        - python-pip
        - graphviz
        - python-rpm
        - yum
    when: ansible_distribution == 'Ubuntu'

  - name: install Nextlinux with PIP
    pip: name=nextlinux
